name: messanger
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  provider: ^6.1.5+1
  get: ^4.7.2
  flutter_riverpod: ^2.6.1
  sqflite: ^2.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  flutter_local_notifications: ^19.4.1
  another_flushbar: ^1.12.31
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.0
  awesome_snackbar_content: ^0.1.7
  curved_navigation_bar: ^1.0.6
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.9.1
  google_fonts: ^6.3.1
  fluttertoast: ^8.2.12
  device_preview: ^1.3.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  firebase_database: ^12.0.1
  cloud_firestore: ^6.0.1
  flutter_animate: ^4.5.2
  country_picker: ^2.0.27
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.2
  shimmer: ^3.0.0
  get_it: ^8.2.0
  introduction_screen: ^4.0.0
  firebase_messaging: ^16.0.1
  googleapis_auth: ^2.0.0
  google_mobile_ads: ^6.0.0
  camera: ^0.11.2
#  facebook_audience_network:
#    git:
#      url: https://github.com/dreamsoftin/facebook_audience_network
#      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.7.2
flutter_native_splash:
  android: true
  ios: true
  color: "#F5F6FA"
  image: assets/images/lo.png
  android_12:
    color: "#F5F6FA"
    image: assets/images/lo.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/lo.png"



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: heading_p
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: heading_c
      fonts:
        - asset: assets/fonts/CascadiaCode-Bold.ttf

    - family: title_p
      fonts:
        - asset: assets/fonts/Inter_28pt-Bold.ttf

#    - family: title_c
#      fonts:
#        - asset: assets/fonts/CascadiaCode-Bold.ttf

    - family: body_p
      fonts:
        - asset: assets/fonts/SueEllenFrancisco-Regular.ttf

    - family: body_r
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: body_c
      fonts:
        - asset: assets/fonts/CascadiaCode-Regular.ttf

