// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-PD-_uXMTCM0uOnPtgHj-OKgeutIoCY',
    appId: '1:695823785598:android:87856138fe6d5cb875822f',
    messagingSenderId: '695823785598',
    projectId: 'messanger-ba53a',
    storageBucket: 'messanger-ba53a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ZCuqZRfdLY219cNIQS_ByazZWxGd5mA',
    appId: '1:695823785598:ios:9cea40386e59e9ef75822f',
    messagingSenderId: '695823785598',
    projectId: 'messanger-ba53a',
    storageBucket: 'messanger-ba53a.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxR9sbNmPTK-iHGZNLzoRYlt_2jw1FCLU',
    appId: '1:695823785598:web:93982facbe42f5c175822f',
    messagingSenderId: '695823785598',
    projectId: 'messanger-ba53a',
    authDomain: 'messanger-ba53a.firebaseapp.com',
    storageBucket: 'messanger-ba53a.firebasestorage.app',
    measurementId: 'G-856B2S2DC7',
  );
}
